name: Format DTS

on:
  push:
    paths:
      - "**/*.dts"
      - "**/*.dtsi"
      - "**/*.overlay"
  pull_request:
    paths:
      - "**/*.dts"
      - "**/*.dtsi"
      - "**/*.overlay"
  workflow_dispatch:

jobs:
  dts-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm i -g dts-linter ts-node

      - name: Run DTS Linter
        id: run-linter
        shell: bash
        run: |
          set -euo pipefail

          # Get all tracked DTS-like files
          mapfile -t FILES < <(git ls-files '*.dts' '*.dtsi' '*.overlay')

          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No DTS files found to lint."
            exit 0
          fi

          echo "Found DTS files:"
          printf '  %s\n' "${FILES[@]}"

          echo "Running dts-linter..."
          # Run the linter
          set +e
          dts-linter \
            --outFile ./diff \
            --diagnostics false \
            --files "${FILES[@]}"
          EXIT_CODE=$?
          set -e

          echo "Linter finished with exit code: $EXIT_CODE"
          echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV

      - name: Upload diff artifact
        uses: actions/upload-artifact@v4
        with:
          name: dts-diff
          path: ./diff

      - name: Fail if linter failed
        if: env.EXIT_CODE == '1'
        run: exit 1
