name: Format DTS

on:
  push:
    paths:
      - "**/*.dts"
      - "**/*.dtsi"
      - "**/*.overlay"
  pull_request:
    paths:
      - "**/*.dts"
      - "**/*.dtsi"
      - "**/*.overlay"
  workflow_dispatch:

jobs:
  dts-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm i -g dts-linter ts-node

      - name: Run DTS Linter
        id: run-linter
        shell: bash
        run: |

          # Run the linter
          set +e
          dts-linter \
            --outFile ./diff \
            --diagnostics false \
            --files "boards/aconno/acn52832/acn52832-pinctrl.dtsi"
          EXIT_CODE=$?
          set -e

          echo "Linter finished with exit code: $EXIT_CODE"
          echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV

      - name: Upload diff artifact
        uses: actions/upload-artifact@v4
        with:
          name: dts-diff
          path: ./diff

      - name: Fail if linter failed
        if: env.EXIT_CODE == '1'
        run: exit 1
