name: Format DTS

on:
  push:
    paths:
      - "**/*.dts"
      - "**/*.dtsi"
      - "**/*.overlay"
  pull_request:
    paths:
      - "**/*.dts"
      - "**/*.dtsi"
      - "**/*.overlay"
  workflow_dispatch:

jobs:
  dts-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm i -g dts-linter

      - name: Find DTS files
        id: find-files
        shell: bash
        run: |
          set -euo pipefail
          echo "Finding DTS files..."
          git ls-files '*.dts' '*.dtsi' '*.overlay' | xargs realpath > dts-files.txt

          if [ ! -s dts-files.txt ]; then
            echo "No DTS files found to lint."
            echo "::set-output name=empty::true"
          else
            echo "Found DTS files:"
            cat dts-files.txt
            echo "::set-output name=empty::false"
          fi

      - name: Run DTS Linter
        if: steps.find-files.outputs.empty != 'true'
        shell: bash
        run: |
          set -euo pipefail
          mapfile -t FILES < dts-files.txt

          echo "Running dts-linter..."
          set +e
          dts-linter --outFile ./diff --formating --files "/home/runner/work/zephyr/zephyr/tests/drivers/adc/adc_api/boards/nrf52840dk_nrf52840.overlay"
          EXIT_CODE=$?
          set -e

          echo "Linter finished with exit code: $EXIT_CODE"
          echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV

      - name: Upload diff artifact
        uses: actions/upload-artifact@v4
        with:
          name: dts-diff
          path: ./diff

      - name: Fail if linter failed
        if: env.EXIT_CODE == '1'
        run: exit 1
